# Imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar a aplicação
COPY . /app/

# Expor a porta
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]
