services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    networks:
      - devops_network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - devops_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - devops_network
    depends_on:
      - prometheus

networks:
  devops_network:
    driver: bridge

volumes:
  mariadb_data:
