global:
  scrape_interval: 15s  # Intervalo de coleta das métricas

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask_app:5000']


  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
